### ISSUE TITLE
Need help before using!

### ISSUE THREAD

**Issue by Limoster** [vdeconinck/QC3Control#6]
I want to make a 12v 2S lipo charger but I need QC 2.0 for the 12V. This is for a very compact audio amplifier and I'd like to make the footprint of the AVR as small as possible. For this i'd need to know how big does a simple program ocupy in the flash memory because I'm limited to 1KB (using sot23-6 Attiny10).
Thanks!

**Comment by vdeconinck** [comment]
I cannot say for sure what size it makes , it depends on the architecture and if some code is already linked due to its usage in other parts of your code. I'd say the simplest way is to test and see.
However, if you only need QC2, then QC2Control - https://github.com/septillion-git/QC2Control - is probably best suited if you are low on resource. In the end, QC2 boils down to 60 lines of C and you can probably reduce it further by just copy/pasting its code into your own. See this file: https://github.com/septillion-git/QC2Control/blob/master/src/QC2Control.cpp
